Repository hmcts/pcq-frontend, pull requests merged in 2020-05, with the labels that each got.

#62 PCQ-246: Correct survey link
  config/default.yaml
Labels: ns:pcq, rel:pcq-frontend-pr-62

#68 Opt out of LD diagnostic reports
  app.js
Labels: ns:pcq, rel:pcq-frontend-pr-68

#71 Bump version to override PR
  charts/pcq-frontend/Chart.yaml
Labels: ns:pcq, rel:pcq-frontend-pr-71

#72 Retry scenario when fail
  test/end-to-end/codecept.conf.js
  test/end-to-end/step_definitions/probatepcqjourney.js
Labels: ns:pcq, rel:pcq-frontend-pr-72

#74 PCQ-288: Increase cluster resources
  Jenkinsfile_CNP
  charts/pcq-frontend/Chart.yaml
  charts/pcq-frontend/values.perftest.template.yaml
Labels: ns:pcq, rel:pcq-frontend-pr-74

#78 Remove err from next()
  app/utils/FeatureToggle.js
  test/unit/testFeatureToggle.js
Labels: ns:pcq, rel:pcq-frontend-pr-78

#60 PCQ-123: List of services on shutter page
  README.md
  app/healthcheck.js
  app/registerIncomingService.js
  app/registeredServices.json
  app/resources/cy/translation/shutterpage.json
  app/resources/en/translation/shutterpage.json
  app/shutter.js
  app/steps/ui/shutterpage/index.js
  app/steps/ui/shutterpage/template.html
  package.json
  test/component/testShutterPage.js
  test/service-stubs/pcq-backend.js
  test/unit/middleware/testRegisterIncomingService.js
  test/unit/testHealthcheck.js
  test/unit/testShutterPage.js
Labels: ns:pcq, rel:pcq-frontend-pr-60

#66 PCQ-250: Text area to text field
  app/resources/cy/translation/religion.json
  app/resources/en/translation/religion.json
  app/steps/ui/religion/template.html
Labels: ns:pcq, rel:pcq-frontend-pr-66

#69 PCQ-249: Update 'Why are we asking this question' text
  app/resources/cy/translation/common.json
  app/resources/en/translation/common.json
Labels: ns:pcq, rel:pcq-frontend-pr-69

#70 PCQ-248: Update content "won't" to "will not"
  app/resources/cy/translation/startpage.json
  app/resources/cy/translation/variable/divorce.json
  app/resources/en/translation/startpage.json
  app/resources/en/translation/variable/cmc.json
  app/resources/en/translation/variable/divorce.json
  app/resources/en/translation/variable/probate.json
  app/resources/en/translation/variable/sscs.json
  test/unit/testStartPage.js
Labels: ns:pcq, rel:pcq-frontend-pr-70

#67 PCQ-262: DAC Issues
  app.js
  app/assets/javascripts/back-button.js
  app/resources/cy/translation/common.json
  app/resources/cy/translation/startpage.json
  app/resources/en/translation/common.json
  app/resources/en/translation/startpage.json
  app/steps/ui/dateofbirth/index.js
  app/steps/ui/dateofbirth/template.html
  app/views/includes/layout.html
  app/views/includes/two_thirds_form.html
  config/default.yaml
  config/testing.yaml
  test/unit/testDateOfBirth.js
  yarn.lock
Labels: ns:pcq, rel:pcq-frontend-pr-67

#77 PCQ-290: LaunchDarkly performance improvements
  app.js
  app/components/launch-darkly.js
  app/utils/FeatureToggle.js
  package.json
  test/data/launchdarkly/simple_flag_data.yaml
  test/unit/components/testLaunchDarkly.js
  test/unit/testFeatureToggle.js
Labels: ns:pcq, rel:pcq-frontend-pr-77

#79 PCQ-287: Preselect DoB radio button
  app/steps/ui/dateofbirth/template.html
Labels: ns:pcq, rel:pcq-frontend-pr-79

#65 PCQ-260: Fix 'None of the above' not deselecting other options on IE
  app/assets/javascripts/mutually-exclusive-checkboxes.js
Labels: ns:pcq, rel:pcq-frontend-pr-65

#80 PCQ-288: Increase resources for all envs
  charts/pcq-frontend/Chart.yaml
  charts/pcq-frontend/values.perftest.template.yaml
  charts/pcq-frontend/values.yaml
Labels: ns:pcq, rel:pcq-frontend-pr-80

#82 PCQ-274: Update smartsurvey link
  config/default.yaml
Labels: ns:pcq, rel:pcq-frontend-pr-82

#83 PCQ-158: Ignore false positives
  audit.json
Labels: ns:pcq, rel:pcq-frontend-pr-83

#85 PCQ-270: Upgrade to Google Tag Manager
  app.js
  app/assets/images/noJS.png
  app/assets/javascripts/ga-tracking.js
  app/views/includes/layout.html
  app/views/includes/scripts.html
  app/views/includes/tag_manager.html
  app/views/includes/tag_manager_nojs.html
  audit.json
  config/custom-environment-variables.yaml
  config/default.yaml
Labels: ns:pcq, rel:pcq-frontend-pr-85

#81 Update mutation and Cross browser testing
  .gitignore
  package.json
  test/accessibility/a11yTest.js
  test/end-to-end/features/crossbrowser.feature
  test/end-to-end/features/smoke.feature
  test/end-to-end/saucelabs.conf.js
  test/end-to-end/smoke.conf.js
  test/mutation/mutation_unittests.conf.js
  yarn.lock
Labels: ns:pcq, rel:pcq-frontend-pr-81

#86 Change locale to lng for consistency with other services
  app.js
  app/resources/cy/translation/common.json
  app/resources/en/translation/common.json
  audit.json
Labels: ns:pcq, rel:pcq-frontend-pr-86

#87 PCQ-154: Update Accessibility Page Content
  app/resources/cy/translation/common.json
  app/resources/cy/translation/static/accessibility.json
  app/resources/en/translation/common.json
  app/resources/en/translation/static/accessibility.json
  app/steps/ui/static/accessibility/template.html
  test/component/static/testAccessibility.js
Labels: ns:pcq, rel:pcq-frontend-pr-87
