Repository hmcts/pcq-frontend, pull requests merged in 2020-08, with the labels that each got.

#118 PCQ-592: Add CORESPONDENT actor to divorce
  app/registeredServices.json
  test/unit/utils/testInvoker.js
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-118

#119 PCQ-545: Add optOut flag
  app/middleware/optOut.js
  app/routes.js
  config/default.yaml
  test/unit/middleware/testOptOut.js
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-119

#120 PCQ-621: Nightly build fixes
  .gitignore
  audit.json
  bin/run-mutation-tests.sh
  package.json
  test/mutation/mutation_unittests.conf.js
  test/mutation/stryker.conf.js
  yarn.lock
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-120

#121 PCQ-621: Use CMC for tests using tokens
  test/unit/middleware/testInvoker.js
  test/unit/middleware/testRegisterIncomingService.js
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-121

#127 updated browser names and versions
  test/crossbrowser/supportedBrowsers.js
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-127

#128 Pcq 625 nightly func
  Jenkinsfile_nightly
  package.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-128

#130 PCQ-639: Updated functional reports in jenkins file
  .gitignore
  Jenkinsfile_CNP
  bin/run-smoke-tests.sh
  config/preview.yaml
  package.json
  test/end-to-end/codecept.conf.js
  test/end-to-end/smoke.conf.js
  yarn.lock
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-130

#132 PCQ-640: Functional and Smoke tests correct URL
  bin/run-functional-tests.sh
  config/custom-environment-variables.yaml
  config/testing.yaml
  package.json
  test/end-to-end/codecept.conf.js
  test/end-to-end/helpers/TestConfigurator.js
  test/end-to-end/smoke.conf.js
  test/end-to-end/smoke/smoketest.js
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-132
