Repository hmcts/pcq-frontend, pull requests merged in 2020-04, with the labels that each got.

#34 DoB field fixes
  app/components/error.js
  app/core/steps/DateStep.js
  app/core/steps/Step.js
  app/steps/ui/dateofbirth/schema.json
  test/component/testDateOfBirth.js
Labels: ns:pcq, rel:pcq-frontend-pr-34

#41 Build fix
  charts/pcq-frontend/Chart.yaml
  charts/pcq-frontend/values.yaml
Labels: ns:pcq, rel:pcq-frontend-pr-41

#42 AKS Migration Steps
  .dockerignore
  .nvmrc
  Dockerfile
  app.js
  app/components/api-utils.js
  app/components/auth.js
  app/components/services.js
  app/config.js
  app/core/steps/DateStep.js
  app/core/steps/Step.js
  app/healthcheck.js
  app/middleware/initSession.js
  app/routes.js
  app/services/FeatureToggle.js
  app/services/Service.js
  app/setupSecrets.js
  app/utils/AsyncFetch.js
  app/utils/FeatureToggle.js
  app/utils/FormatUrl.js
  charts/pcq-frontend/Chart.yaml
  charts/pcq-frontend/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  config/testing.yaml
  package.json
  server.js
  test/accessibility/a11yTest.js
  test/component/static/testAccessibility.js
  test/component/static/testCookies.js
  test/component/static/testPrivacyPolicy.js
  test/component/static/testTermsAndConditions.js
  test/component/testApi-Utils.js
  test/component/testDateOfBirth.js
  test/component/testDisability.js
  test/component/testDisabilityImplications.js
  test/component/testDisabilityImplicationsAreas.js
  test/component/testEnglishLevel.js
  test/component/testEthnicGroup.js
  test/component/testEthnicGroupAsian.js
  test/component/testEthnicGroupBlack.js
  test/component/testEthnicGroupMixed.js
  test/component/testEthnicGroupOther.js
  test/component/testEthnicGroupWhite.js
  test/component/testGender.js
  test/component/testLanguage.js
  test/component/testMaritalStatus.js
  test/component/testPregnant.js
  test/component/testReligion.js
  test/component/testSex.js
  test/component/testSexualOrientation.js
  test/component/testShutterPage.js
  test/component/testStartPage.js
  test/service-stubs/feature-toggles.js
  test/service-stubs/orchestration.js
  test/unit/middleware/testRegisterIncomingService.js
  test/unit/services/testFormData.js
  test/unit/testFeatureToggleService.js
  test/unit/testSetupSecrets.js
  test/util/TestWrapper.js
  yarn.lock
Labels: ns:pcq, rel:pcq-frontend-pr-42

#43 PCQ-56: Add Welsh translations
  app/resources/cy/translation/common.json
  app/resources/cy/translation/dateofbirth.json
  app/resources/cy/translation/disability.json
  app/resources/cy/translation/disabilityimplications.json
  app/resources/cy/translation/disabilityimplicationsareas.json
  app/resources/cy/translation/endpage.json
  app/resources/cy/translation/englishlevel.json
  app/resources/cy/translation/ethnicasian.json
  app/resources/cy/translation/ethnicblack.json
  app/resources/cy/translation/ethnicgroup.json
  app/resources/cy/translation/ethnicmixed.json
  app/resources/cy/translation/ethnicother.json
  app/resources/cy/translation/ethnicwhite.json
  app/resources/cy/translation/gender.json
  app/resources/cy/translation/language.json
  app/resources/cy/translation/maritalstatus.json
  app/resources/cy/translation/pregnant.json
  app/resources/cy/translation/religion.json
  app/resources/cy/translation/sex.json
  app/resources/cy/translation/sexualorientation.json
  app/resources/cy/translation/startpage.json
  app/resources/en/translation/startpage.json
  app/steps/ui/startpage/template.html
Labels: ns:pcq, rel:pcq-frontend-pr-43

#44 PCQ-172: JWT to expected format
  app/components/auth.js
  app/middleware/registerIncomingService.js
  config/default.yaml
Labels: ns:pcq, rel:pcq-frontend-pr-44

#48 Increase Redis version to 10.5.7
  charts/pcq-frontend/Chart.yaml
  charts/pcq-frontend/requirements.yaml
Labels: ns:pcq, rel:pcq-frontend-pr-48

#47 Minor Issue Fixes
  app/steps/ui/dateofbirth/index.js
  app/steps/ui/endpage/index.js
  app/steps/ui/language/index.js
  app/steps/ui/startpage/index.js
  test/component/testEndPage.js
  test/component/testStartPage.js
  test/unit/testDateOfBirth.js
  test/unit/testEndPage.js
  test/unit/testLanguage.js
  test/unit/testStartPage.js
Labels: ns:pcq, rel:pcq-frontend-pr-47

#50 PCQ-122: Sanitize request body
  app.js
  app/middleware/sanitizeRequestBody.js
  package.json
  test/unit/middleware/testSanatizeRequestBody.js
  yarn.lock
Labels: ns:pcq, rel:pcq-frontend-pr-50

#52 PCQ-212: LaunchDarkly implementation
  .gitignore
  README.md
  app.js
  app/components/services.js
  app/services/FeatureToggle.js
  app/setupSecrets.js
  app/shutter.js
  app/utils/FeatureToggle.js
  charts/pcq-frontend/Chart.yaml
  charts/pcq-frontend/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  config/dev_template.yaml
  package.json
  test/accessibility/a11yTest.js
  test/component/testShutterPage.js
  test/data/launchdarkly/simple_flag_data.yaml
  test/unit/testFeatureToggle.js
  test/unit/testFeatureToggleService.js
  test/util/TestWrapper.js
  yarn.lock
Labels: ns:pcq, rel:pcq-frontend-pr-52

#53 PCQ-63: Prefix HTTPS on returnUrl && Bug fix
  app/components/string-utils.js
  app/core/steps/Step.js
  app/middleware/registerIncomingService.js
  test/unit/middleware/testRegisterIncomingService.js
  test/unit/testStringUtils.js
Labels: ns:pcq, rel:pcq-frontend-pr-53

#33 PCQ-158: Security scan fixes
  audit.json
  security.sh
Labels: ns:pcq, rel:pcq-frontend-pr-33

#55 Updated smoke tests
  bin/run-smoke-tests.sh
  package.json
  test/config.js
  test/end-to-end/smoke.conf.js
  test/end-to-end/smoke/smoketest.js
  test/end-to-end/smokefeature/smoke.feature
  test/smoke/healthcheck.js
  yarn.lock
Labels: ns:pcq, rel:pcq-frontend-pr-55

#56 PCQ-204: Use HMCTS NodeJs Healthcheck
  Jenkinsfile_CNP
  app.js
  app/core/steps/Step.js
  app/healthcheck.js
  app/services/FormData.js
  charts/pcq-frontend/Chart.yaml
  charts/pcq-frontend/values.aat.template.yaml
  charts/pcq-frontend/values.preview.template.yaml
  charts/pcq-frontend/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  package.json
  test/unit/services/testFormData.js
  test/unit/testHealthcheck.js
  yarn.lock
Labels: ns:pcq, rel:pcq-frontend-pr-56

#57 PCQ-188: Show error on invalid year
  app/steps/ui/dateofbirth/index.js
  test/component/testDateOfBirth.js
  test/unit/testDateOfBirth.js
Labels: ns:pcq, rel:pcq-frontend-pr-57

#45 PCQ-33: Service down implementation
  README.md
  app/core/steps/Step.js
  app/healthcheck.js
  app/journeys/README.md
  app/middleware/initSession.js
  app/middleware/registerIncomingService.js
  app/middleware/setJourney.js
  app/middleware/validateParams.js
  app/registeredServices.json
  app/resources/cy/translation/shutterpage.json
  app/resources/en/translation/shutterpage.json
  app/routes.js
  app/shutter.js
  app/steps/ui/shutterpage/index.js
  app/steps/ui/shutterpage/template.html
  app/utils/FeatureToggle.js
  charts/pcq-frontend/Chart.yaml
  charts/pcq-frontend/values.yaml
  config/default.yaml
  test/unit/middleware/testRegisterIncomingService.js
  test/unit/middleware/testSetJourney.js
  test/unit/middleware/testValidateParams.js
  test/unit/testFeatureToggle.js
  test/unit/testHealthcheck.js
  test/unit/testShutterPage.js
Labels: ns:pcq, rel:pcq-frontend-pr-45

#61 Revert temporary change to backend url
  charts/pcq-frontend/Chart.yaml
  charts/pcq-frontend/values.yaml
Labels: ns:pcq, rel:pcq-frontend-pr-61

#58 PCQ-247: Reset the session for new service
  app/middleware/initSession.js
  app/registerIncomingService.js
Labels: ns:pcq, rel:pcq-frontend-pr-58
