Repository hmcts/pcq-frontend, pull requests merged in 2020-09, with the labels that each got.

#123 PCQ-558: Remove 'Force Offline' toggle
  app/routes.js
  app/shutter.js
  config/default.yaml
  config/testing.yaml
  test/accessibility/a11yTest.js
  test/component/testShutterPage.js
  test/unit/utils/testFeatureToggle.js
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-123

#122 PCQ-557: Remove 'Enforce Parameters' toggle
  app/middleware/validateParams.js
  config/default.yaml
  test/accessibility/a11yTest.js
  test/component/common/testCommonContent.js
  test/component/testEndPage.js
  test/unit/middleware/testValidateParams.js
  test/util/TestWrapper.js
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-122

#135 Nightly fix
  audit.json
  package.json
  yarn.lock
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-135

#125 PCQ-559: Remove 'Invoker' toggle
  app/middleware/invoker.js
  config/default.yaml
  test/unit/middleware/testInvoker.js
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-125

#136 PCQ-650: Fix mutation tests
  config/default.yaml
  test/unit/middleware/testRegisterIncomingService.js
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-136

#137 PCQ-646: Change backend health url to readiness
  app/healthcheck.js
  test/service-stubs/pcq-backend.js
  test/unit/testHealthcheck.js
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-137

#138 Nightly fix: Add false positives
  audit.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-138

#133 PCQ-624: Allow static pages to be accessed without journey
  app/middleware/validateParams.js
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-133

#141 Nightly Security Scan Fixes
  app/resources/cy/translation/static/accessibility.json
  app/resources/cy/translation/static/cookies.json
  app/resources/cy/translation/static/privacy.json
  app/resources/cy/translation/static/terms.json
  app/resources/en/translation/static/accessibility.json
  app/resources/en/translation/static/cookies.json
  app/resources/en/translation/static/privacy.json
  app/resources/en/translation/static/terms.json
  audit.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-141

#142 Nightly Security Scan: Add false positives
  audit.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-142

#144 PCQ656 - Updated the divorce text for corespondent
  app/resources/cy/translation/variable/divorce.json
  app/resources/en/translation/variable/divorce.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-144

#146 Security fix
  audit.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-146

#147 added false positives
  audit.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-147

#149 false positive added
  audit.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-149

#150 Add false positives to audit.json
  audit.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-150
