Repository hmcts/pcq-frontend, pull requests merged in 2022-10, with the labels that each got.

#340 PCQ-1474 Upgrade Terraform Version
  infrastructure/.terraform-version
  package.json
Labels: ns:pcq, prd:pcq, add-or-update, rel:pcq-frontend-pr-340

#342 PCQ-1531 Remove 'actualStatus' from health endpoint
  app/healthcheck.js
  test/unit/middleware/testRegisterIncomingService.js
  test/unit/testHealthcheck.js
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-342

#343 PCQ-1536 Disable nightly build during weekend
  Jenkinsfile_nightly
  package.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-343

#339 PCQ-1473: Yarn V3 Upgrade
  .gitignore
  .yarn/releases/yarn-3.2.3.cjs
  .yarnrc.yml
  app.js
  app/healthcheck.js
  package.json
  test/unit/testHealthcheck.js
  yarn.lock
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-339

#345 PCQ-1542 Update GA Nonce Control
  app/core/runners/UIStepRunner.js
  app/routes.js
  app/views/includes/tag_manager.html
  config/default.yaml
  package.json
  test/unit/core/testOptionGetRunner.js
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-345

#348 PCQ-1542 Add GA CSP directives
  app.js
  package.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-348

#347 PCQ-1545 Fix mutation tests
  bin/githooks/pre-commit
  package.json
  test/mutation/stryker.conf.js
  test/util/TestWrapper.js
  yarn.lock
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-347

#346 PCQ-1543 Upgrade GOVUK Frontend framework to V4
  app/assets/sass/application-ie8.scss
  app/assets/sass/application.scss
  package.json
  yarn.lock
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-346

#350 PCQ-1532 Update terms & conditions - service management
  app/resources/cy/translation/static/terms.json
  app/resources/en/translation/static/terms.json
  package.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-350

#352 PCQ-84 changing ET redirect link to production
  app/registeredServices.json
  package.json
  test/unit/testShutterPage.js
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-352
