Repository hmcts/pcq-frontend, pull requests merged in 2022-05, with the labels that each got.

#296 PCQ-1422-pcq-frontend-security-scan-40024_SQL-Injection
  audit.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-296

#293 PCQ-1287 Remove 'New cookie feature' toggle
  app/core/steps/Step.js
  app/routes.js
  app/steps/ui/static/cookies/index.js
  app/steps/ui/static/cookies/old-template.html
  app/steps/ui/static/cookies/template.html
  app/views/includes/layout.html
  config/default.yaml
  package.json
  test/component/static/testCookies.js
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-293

#299 PCQ-970 Fix cookie form V1 changes
  app/assets/javascripts/cookie-v1.js
  app/steps/ui/static/cookies/template.html
  package.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-299

#300 PCQ-1370 Accessibilty change
  app/resources/cy/translation/static/accessibility.json
  app/resources/en/translation/static/accessibility.json
  package.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-300

#301 PCQ-1420-security-scan-fail-cookie_bundle_v1
  audit.json
  package.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-301

#297 PCQ-971 DTRUM Opt-out user action (under toggle)
  app/assets/javascripts/dtrum-optout.js
  app/routes.js
  app/steps/ui/startpage/index.js
  app/steps/ui/startpage/template.html
  config/default.yaml
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-297

#302 PCQ-971 Set cookie status to determine cookie pref
  app/assets/javascripts/dtrum-optout.js
  package.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-302

#295 PCQ-1308 frontend setup
  app/journeys/et.js
  app/registeredServices.json
  app/resources/cy/translation/shutterpage.json
  app/resources/cy/translation/static/accessibility.json
  app/resources/cy/translation/variable/et.json
  app/resources/en/translation/shutterpage.json
  app/resources/en/translation/static/accessibility.json
  app/resources/en/translation/variable/et.json
  app/setupSecrets.js
  app/steps/ui/static/accessibility/template.html
  charts/pcq-frontend/Chart.yaml
  charts/pcq-frontend/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  test/component/static/testAccessibility.js
  test/component/testShutterPage.js
  test/unit/core/testServiceData.json
  test/unit/services/testServiceInvokerData.json
  test/unit/testShutterPage.js
  test/unit/utils/testInvoker.js
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-295

#303 PCQ-971 Add timestamp for dtrum optout js file
  app/steps/ui/startpage/index.js
  app/steps/ui/startpage/template.html
  package.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-303
