Repository hmcts/pcq-frontend, pull requests merged in 2022-11, with the labels that each got.

#349 PCQ-1547 Update version file
  .dockerignore
  .gitignore
  Dockerfile
  app/healthcheck.js
  createVersionFile.js
  package.json
  test/mutation/stryker.conf.js
  test/route/app/healthcheck.int.js
  yarn.lock
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-349

#353 PCQ-1594 Remove 'Pregnancy' question from Adoption journey
  app/journeys/adoption.js
  package.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-353

#354 PCQ-1593 Add SonarQube badges and Overview section
  README.md
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-354

#355 PCQ-1595 Cleanup helm release on success
  .github/PULL_REQUEST_TEMPLATE.md
  Jenkinsfile_CNP
  package.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-355

#357 PCQ-1600 upgrading helm releases
  .nvmrc
  charts/pcq-frontend/Chart.yaml
  package.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-357

#356 PCQ-1601 Update app insights functionality
  app.js
  app/components/app-insights.js
  charts/pcq-frontend/Chart.yaml
  charts/pcq-frontend/values.yaml
  package.json
  sonar-project.properties
  yarn.lock
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-356

#167 PCQ-732 Move cnp-module-redis to master
  infrastructure/main.tf
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-167, no-changes
