Repository hmcts/pcq-frontend, pull requests merged in 2022-04, with the labels that each got.

#285 PCQ-967 pcq-frontend security scan vulnerability fix
  audit.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-285

#284 PCQ-973 Fixes for dynatrace user experience
  app.js
  app/assets/javascripts/cookie.js
  package.json
  yarn.lock
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-284

#289 PCQ-1450: Fix vulnerabilities.
  audit.json
  package.json
  security.sh
  yarn.lock
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-289

#287 PCQ-1292 Add Session Parameters for Dynatrace
  app.js
  app/core/runners/UIStepRunner.js
  app/routes.js
  app/views/includes/layout.html
  app/views/includes/scripts.html
  config/default.yaml
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-287

#291 PCQ-1292 Move app version into HTML el
  app/views/includes/layout.html
  app/views/includes/scripts.html
  package.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-291

#292 PCQ-1451: Dependency fixes
  package.json
  yarn.lock
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-292
