Repository hmcts/pcq-frontend, pull requests merged in 2022-02, with the labels that each got.

#253 PCQ-1236 Updating HMCTS Library to latest vesrion
  package.json
  yarn.lock
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-253

#254 PCQ-1290 Dependency check
  package.json
  yarn.lock
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-254

#257 PCQ-1290 Yarn audit fixes
  package.json
  test/mutation/stryker.conf.js
  yarn-audit-known-issues
  yarn.lock
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-257

#239 Pcq 1137
  test/unit/services/testServiceInvoker.js
  test/unit/services/testServiceInvokerData.json
  yarn.lock
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-239

#258 PCQ-1143 Istanbul code Coverage
  package.json
  yarn.lock
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-258

#260 Yarn audit fixes
  package.json
  yarn.lock
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-260

#247 PCQ-749: Add user consent cookie banner and cookie preferences saving feature.
  app.js
  app/assets/javascripts/cookie.js
  app/assets/javascripts/invoker.js
  app/core/steps/Step.js
  app/middleware/initSession.js
  app/resources/cy/translation/common.json
  app/resources/cy/translation/dateofbirth.json
  app/resources/cy/translation/errors/404.json
  app/resources/cy/translation/errors/500.json
  app/resources/cy/translation/static/accessibility.json
  app/resources/cy/translation/static/cookies.json
  app/resources/cy/translation/static/privacy.json
  app/resources/cy/translation/static/terms.json
  app/resources/en/translation/common.json
  app/resources/en/translation/dateofbirth.json
  app/resources/en/translation/errors/404.json
  app/resources/en/translation/errors/500.json
  app/resources/en/translation/static/accessibility.json
  app/resources/en/translation/static/cookies.json
  app/resources/en/translation/static/privacy.json
  app/resources/en/translation/static/terms.json
  app/routes.js
  app/steps/ui/static/cookies/index.js
  app/steps/ui/static/cookies/new-template.html
  app/steps/ui/static/cookies/old-template.html
  app/views/includes/cookie-banner.html
  app/views/includes/layout.html
  config/default.yaml
  package.json
  test/accessibility/a11yTest.js
  test/component/static/testCookies.js
  test/unit/testEndPage.js
  test/unit/testStartPage.js
  test/util/TestWrapper.js
  yarn.lock
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-247

#261 Chart Nodejs upgrade
  charts/pcq-frontend/Chart.yaml
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-261

#262 Update security.sh for debugging
  security.sh
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-262

#264 Update security.sh
  security.sh
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-264
