Repository hmcts/pcq-frontend, pull requests merged in 2022-06, with the labels that each got.

#305 PCQ-1262 Setup SJS service
  app/journeys/online_plea.js
  app/registeredServices.json
  app/resources/cy/translation/shutterpage.json
  app/resources/cy/translation/static/accessibility.json
  app/resources/cy/translation/variable/online_plea.json
  app/resources/en/translation/shutterpage.json
  app/resources/en/translation/static/accessibility.json
  app/resources/en/translation/variable/online_plea.json
  app/setupSecrets.js
  app/steps/ui/static/accessibility/template.html
  charts/pcq-frontend/Chart.yaml
  charts/pcq-frontend/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  package.json
  test/component/testShutterPage.js
  test/unit/core/testServiceData.json
  test/unit/services/testServiceInvokerData.json
  test/unit/testShutterPage.js
  test/unit/utils/testInvoker.js
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-305

#306 PCQ-912 Exclude RUM Beacon POST calls from CSRF checks
  app.js
  package.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-306

#307 PCQ-912 Exclude RUM beacon calls from CSRF checks - Prod
  app.js
  package.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-307

#308 PCQ-1335 Configuring renovate for frontend
  package.json
  renovate/configure/renovate.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-308

#309 PCQ-914 Security Scan fix
  audit.json
  package.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-309
