Repository hmcts/pcq-frontend, pull requests merged in 2022-03, with the labels that each got.

#272 PCQ-816 Security.sh change
  Jenkinsfile_nightly
  audit.json
  security.sh
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-272

#273 PCQ-816 audit.json change
  audit.json
  yarn-audit-known-issues
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-273

#274 PCQ-816 audit.json change
  audit.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-274

#275 Yarn audit fix
  yarn-audit-known-issues
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-275

#277 yarn audit fix
  yarn-audit-known-issues
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-277

#276 ajv upgrade
  app/core/steps/ValidationStep.js
  app/steps/ui/dateofbirth/schema.json
  app/steps/ui/disability/schema.json
  app/steps/ui/disabilityimplications/schema.json
  app/steps/ui/disabilityimplicationsareas/schema.json
  app/steps/ui/englishlevel/schema.json
  app/steps/ui/ethnicasian/schema.json
  app/steps/ui/ethnicblack/schema.json
  app/steps/ui/ethnicgroup/schema.json
  app/steps/ui/ethnicmixed/schema.json
  app/steps/ui/ethnicother/schema.json
  app/steps/ui/ethnicwhite/schema.json
  app/steps/ui/gender/schema.json
  app/steps/ui/language/schema.json
  app/steps/ui/maritalstatus/schema.json
  app/steps/ui/pregnant/schema.json
  app/steps/ui/religion/schema.json
  app/steps/ui/sex/schema.json
  app/steps/ui/sexualorientation/schema.json
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-276

#271 PCQ-1135 Added test for Welsh e2e
  test/end-to-end/features/probate.feature
  test/end-to-end/pages/dateofbirth/dateofbirth.js
  test/end-to-end/pages/disability/yes.js
  test/end-to-end/pages/disabilityimplications/yeslimitedalot.js
  test/end-to-end/pages/disabilityimplicationsareas/disabilityimplicationsareas.js
  test/end-to-end/pages/endpage/endpage.js
  test/end-to-end/pages/ethnicgroup/whiteethnicgroup.js
  test/end-to-end/pages/gendersameassex/yesgendersameassex.js
  test/end-to-end/pages/language/englishorwelsh.js
  test/end-to-end/pages/maritalstatus/yes.js
  test/end-to-end/pages/pregnant/yes.js
  test/end-to-end/pages/religion/christian.js
  test/end-to-end/pages/sex/male.js
  test/end-to-end/pages/sexualorientation/heterosexualorstraight.js
  test/end-to-end/pages/startpage/startpage.js
  test/end-to-end/pages/whiteethnicgroup/englishwelshscottishirishbritish.js
  test/end-to-end/step_definitions/probatepcqjourney.js
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-271

#278 Add pre-commit hook to bump patch version
  bin/githooks/pre-commit
  bin/preinstall.sh
  package.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-278

#280 PCQ-1109 Fix Sonar issues
  app/core/steps/Step.js
  app/utils/AsyncFetch.js
  app/utils/FeatureToggle.js
  app/utils/FormatUrl.js
  test/unit/middleware/testOptOut.js
  test/unit/middleware/testSanatizeRequestBody.js
  test/unit/services/testService.js
  test/unit/utils/testAsyncFetch.js
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-280

#281 PCQ-817 Security scan fix
  audit.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-281

#282 PCQ-960 Dependency check fix
  package.json
  yarn.lock
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-282
