Repository hmcts/pcq-frontend, pull requests merged in 2022-08, with the labels that each got.

#332 PCQ-1521 Accessibility Page for ET
  app/resources/cy/translation/static/accessibility.json
  package.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-332

#333 PCQ-1522 Accessibility for IAC
  app/resources/cy/translation/static/accessibility.json
  package.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-333

#334 PCQ-1524 Dependency check fix
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-334

#336 PCQ-1525 Fix Sonar Code Coverage
  package.json
  sonar-project.properties
  yarn.lock
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-336

#338 Add backstage configuration file
  catalog-info.yaml
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-338

#311 PCQ-1427 Cross Browser Test Dependency Upgrades
  .gitignore
  package.json
  test/crossbrowser/supportedBrowsers.js
  test/end-to-end/codecept.conf.js
  test/end-to-end/helpers/JSWait.js
  test/end-to-end/helpers/PuppeteerHelper.js
  test/end-to-end/helpers/SauceLabsReportingHelper.js
  test/end-to-end/saucelabs.conf.js
  yarn.lock
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-311
