Repository hmcts/pcq-frontend, pull requests merged in 2022-07, with the labels that each got.

#304 PCQ-971 Cookie status null check
  app/assets/javascripts/dtrum-optout.js
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-304

#312 PCQ-1419 Upgrade NodeJS to Version 16
  .dockerignore
  .gitignore
  Dockerfile
  README.md
  app/healthcheck.js
  createVersionFile.js
  package.json
  test/mutation/stryker.conf.js
  yarn.lock
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-312

#314 Yarn audit fixes
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-314

#315 PCQ-940 dependency check
  package.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-315

#317 PCQ-Frontend Security scan fix
  audit.json
  package.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-317

#318 PCQ-896 configuring renovate
  .github/renovate.json
  package.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-318

#324 PCQ-932 dependency check fix
  package.json
  yarn-audit-known-issues
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-324

#325 Upgrade nodejs chart version
  charts/pcq-frontend/Chart.yaml
  package.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-325

#329 PCQ-1463 Security Scan fix
  audit.json
  package.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-329

#330 PCQ-1463 Security Scan fix
  audit.json
  package.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-330
