Repository hmcts/pcq-frontend, pull requests merged in 2023-05, with the labels that each got.

#441 PCQ-1506 Remove actor subject
  app/registeredServices.json
  package.json
  test/unit/services/testServiceInvokerData.json
  test/unit/utils/testInvoker.js
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-441

#447 PCQ-1684 private law setup in PCQ
  app/journeys/prl_ca.js
  app/journeys/prl_da.js
  app/registeredServices.json
  app/resources/cy/translation/shutterpage.json
  app/resources/cy/translation/static/accessibility.json
  app/resources/cy/translation/variable/prl_ca.json
  app/resources/cy/translation/variable/prl_da.json
  app/resources/en/translation/shutterpage.json
  app/resources/en/translation/static/accessibility.json
  app/resources/en/translation/variable/prl_ca.json
  app/resources/en/translation/variable/prl_da.json
  app/setupSecrets.js
  app/steps/ui/static/accessibility/template.html
  charts/pcq-frontend/Chart.yaml
  charts/pcq-frontend/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  node_modules/.cache/nyc/prl_ca-fd28636c2be15306e6e609fb670740612b6f8f2b461d89b5baa33a94ecdb1fd6.js
  node_modules/.cache/nyc/prl_da-eb321b43467ade1780d23829bc5e334f85e047b24f7de76a66787d0629efa255.js
  node_modules/.cache/nyc/setupSecrets-721a5e840c139e722996ee61e6a86c22cdbf95de58c2cc5aec910f7dd7b078c3.js
  package.json
  test/component/static/testAccessibility.js
  test/component/testShutterPage.js
  test/unit/core/testServiceData.json
  test/unit/services/testServiceInvokerData.json
  test/unit/testShutterPage.js
  test/unit/utils/testInvoker.js
Labels: ns:pcq, prd:pcq, keep-helm, rel:pcq-frontend-pr-447

#457 DTSPO-13810 reschedule jenkins nightly builds
  Jenkinsfile_nightly
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-457

#458 DTSPO-13810 reschedule nightlybuilds to start at 8am
  Jenkinsfile_nightly
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-458

#462 PCQ-1735 Security scan fix
  audit.json
  package.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-462
