Repository hmcts/pcq-frontend, pull requests merged in 2023-06, with the labels that each got.

#461 CMC Citizen UI PCQ integration.
  app/journeys/civil-citizen-ui.js
  app/registeredServices.json
  app/resources/cy/translation/static/accessibility.json
  app/resources/cy/translation/variable/civil-citizen-ui.json
  app/resources/en/translation/static/accessibility.json
  app/resources/en/translation/variable/civil-citizen-ui.json
  app/setupSecrets.js
  app/steps/ui/static/accessibility/template.html
  charts/pcq-frontend/Chart.yaml
  charts/pcq-frontend/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  package.json
  test/component/static/testAccessibility.js
  test/unit/core/testServiceData.json
  test/unit/services/testServiceInvokerData.json
  test/unit/utils/testInvoker.js
Labels: ns:pcq, prd:pcq, keep-helm, rel:pcq-frontend-pr-461

#476 Revert "Merge pull request #475 from hmcts/dependabot/npm_and_yarn/ba…
  .pnp.cjs
  .yarn/cache/@babel-code-frame-npm-7.22.5-b36f88d6f9-cfe804f518.zip
  .yarn/cache/@babel-generator-npm-7.22.5-0e87a1a822-efa64da70c.zip
  .yarn/cache/@babel-helper-environment-visitor-npm-7.22.5-7bc52eec61-248532077d.zip
  .yarn/cache/@babel-helper-function-name-npm-7.22.5-8a1a69b63d-6b1f6ce1b1.zip
  .yarn/cache/@babel-helper-hoist-variables-npm-7.22.5-6db3192347-394ca191b4.zip
  .yarn/cache/@babel-helper-split-export-declaration-npm-7.22.5-5e708abd3e-d10e05a02f.zip
  .yarn/cache/@babel-helper-string-parser-npm-7.22.5-448ff0e489-836851ca5e.zip
  .yarn/cache/@babel-helper-validator-identifier-npm-7.22.5-4536624779-7f0f301134.zip
  .yarn/cache/@babel-highlight-npm-7.22.5-3182ccc1fe-f61ae6de6e.zip
  .yarn/cache/@babel-parser-npm-7.22.5-6f8647af64-470ebba516.zip
  .yarn/cache/@babel-template-npm-7.22.5-358c44dc9d-c574641016.zip
  .yarn/cache/@babel-traverse-npm-7.22.5-071d471ccd-560931422d.zip
  .yarn/cache/@babel-types-npm-7.22.5-d1e4264bef-c13a9c1dc7.zip
  package.json
  yarn.lock
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-476

#483 PCQ-1741 suppress qs issue
  .nvmrc
  Dockerfile
  package.json
  yarn-audit-known-issues
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-483

#485 Pcq 1741
  audit.json
  infrastructure/main.tf
  package.json
Labels: ns:pcq, prd:pcq, no-changes, rel:pcq-frontend-pr-485

#487 update yarn-audit-known-issues file
  package.json
  yarn-audit-known-issues
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-487

#491 PCQ-1646 change redirect link to production url
  app/registeredServices.json
  package.json
  test/unit/testShutterPage.js
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-491
