Repository hmcts/pcq-frontend, pull requests merged in 2023-12, with the labels that each got.

#756 PCQ-1846 adding scripts for dynatrace monitoring
  app/views/includes/scripts.html
  package.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-756

#757 PCQ-1846 adding scripts for dynatrace monitoring with integrity only …
  app/views/includes/scripts.html
  package.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-757

#762 Update audit.json for security scan fix
  audit.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-762

#765 Update audit.json
  audit.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-765

#768 PCQ-1850 - added fingerprints into audit.json file
  audit.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-768

#770 PCQ-1850 - added fingerprints into audit.json file
  audit.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-770

#771 Revert Back govuk-frontend upgrade from 5.0.0 to 4.7.0
  .pnp.cjs
  package.json
  yarn.lock
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-771

#773 Update audit.json
  audit.json
  package.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-773

#774 Update Chart.yaml
  charts/pcq-frontend/Chart.yaml
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-774

#775 PCQ-1850 - added one further fingerprint into audit.json file
  audit.json
  charts/pcq-frontend/Chart.yaml
  package.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-775

#786 Update audit.json to fix security scan
  audit.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-786

#787 PCQ-1853 adding real user monitoring for aat
  app/views/includes/scripts.html
  package.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-787

#789 PCQ-1853 adding aat file to pick aat environment
  config/aat.yaml
  package.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-789

#790 PCQ-1835 changing to testing env
  app/views/includes/scripts.html
  charts/pcq-frontend/Chart.yaml
  config/aat.yaml
  package.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-790

#791 PCQ-1853 finding env
  app/views/includes/scripts.html
  charts/pcq-frontend/values.aat.template.yaml
  package.json
Labels: ns:pcq, prd:pcq, enable_keep_helm, rel:pcq-frontend-pr-791

#792 PCQ-1853 revert chages
  app/views/includes/scripts.html
  charts/pcq-frontend/values.aat.template.yaml
  package.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-792
