Repository hmcts/pcq-frontend, pull requests merged in 2023-11, with the labels that each got.

#705 PCQ-1841 - added 3 fingerprints into audit.json file in order to fix …
  audit.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-705

#706 PCQ-1841 - added 1 fingerprint into audit.json file
  audit.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-706

#707 PCQ-1841 - added 2 fingerprints into audit.json file
  audit.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-707

#708 PCQ-1824 remove dependabot config
  .github/dependabot.yml
  package.json
Labels: ns:pcq, prd:pcq, add-or-update, rel:pcq-frontend-pr-708

#726 Pcq 1844 remove obsolete csp
  charts/pcq-frontend/Chart.yaml
  package.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-726
