Repository hmcts/pcq-frontend, pull requests merged in 2023-08, with the labels that each got.

#524 PCQ-1786-fix-fortify-scan
  package.json
  test/java/build.gradle
  test/java/gradle/wrapper/gradle-wrapper.properties
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-524

#525 PCQ-1788 Security scan fix
  audit.json
  package.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-525

#526 PCQ-1785 empty PR to start application
  README.md
  package.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-526

#531 PCQ-1792 Security scan fix
  audit.json
  package.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-531
