Repository hmcts/pcq-frontend, pull requests merged in 2024-05, with the labels that each got.

#1026 PCQ-1898 - added 1 fingerprint into audit.json file
  audit.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-1026

#1029 Disable spot instances
  charts/pcq-frontend/Chart.yaml
  charts/pcq-frontend/values.yaml
  package.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-1029

#980 PCQ-1454 added adoption accessibility
  app/resources/cy/translation/static/accessibility.json
  app/resources/en/translation/static/accessibility.json
  app/steps/ui/static/accessibility/template.html
  test/component/static/testAccessibility.js
Labels: ns:pcq, prd:pcq, enable_keep_helm, rel:pcq-frontend-pr-980

#1035 PCQ-1900 remove accept-ranges header
  app.js
  package.json
Labels: ns:pcq, prd:pcq, enable_keep_helm, rel:pcq-frontend-pr-1035

#1037 PCQ-1900 enable gzip compression
  .pnp.cjs
  app.js
  package.json
  yarn.lock
Labels: ns:pcq, prd:pcq, enable_keep_helm, aat/add-or-update, prod/no-changes, rel:pcq-frontend-pr-1037

#1039 Add missing start page paragraph for prl.
  .gitignore
  app/resources/cy/translation/variable/prl_ca.json
  app/resources/cy/translation/variable/prl_da.json
  app/resources/en/translation/variable/prl_ca.json
  app/resources/en/translation/variable/prl_da.json
  package.json
  test/unit/core/testServiceData.json
Labels: ns:pcq, prd:pcq, aat/add-or-update, prod/no-changes, rel:pcq-frontend-pr-1039

#1049 LAU-841 enable security scan once a month only
  Jenkinsfile_nightly
  package.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-1049

#1050 PCQ-1900 inject dynatrace script manually
  app/views/includes/scripts.html
  package.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-1050

#1046 added worker src
  app.js
Labels: ns:pcq, prd:pcq, enable_keep_helm, aat/add-or-update, prod/no-changes, rel:pcq-frontend-pr-1046

#1055 use yarn builder to install playwright
  Jenkinsfile_nightly
  package.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-1055
