Repository hmcts/pcq-frontend, pull requests merged in 2024-01, with the labels that each got.

#801 PCQ-1853 adding hidden element for environment
  app/views/includes/scripts.html
  charts/pcq-frontend/values.aat.template.yaml
  charts/pcq-frontend/values.preview.template.yaml
  package.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-801

#802 Pcq 1853
  config/aat.yaml
  package.json
Labels: ns:pcq, prd:pcq, enable_keep_helm, rel:pcq-frontend-pr-802

#803 PCQ-1853 adding environment
  charts/pcq-frontend/Chart.yaml
  config/aat.yaml
  package.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-803

#804 PCQ-1853 adding Dynatrace Script
  app/views/includes/scripts.html
  charts/pcq-frontend/values.aat.template.yaml
  config/aat.yaml
  package.json
  sonar-project.properties
Labels: ns:pcq, prd:pcq, add-or-update, enable_keep_helm, rel:pcq-frontend-pr-804

#809 Bump chart version
  charts/pcq-frontend/Chart.yaml
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-809

#815 sort audit.json alphabetically
  audit.json
  package.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-815

#816 Pcq 1740 bump helmet
  .pnp.cjs
  .yarn/cache/bowser-npm-2.9.0-043d25ec0d-ffb068f11e.zip
  .yarn/cache/camelize-npm-1.0.0-5eda108776-769f8d1007.zip
  .yarn/cache/content-security-policy-builder-npm-2.1.0-0bb05bcc01-375944b111.zip
  .yarn/cache/dasherize-npm-2.0.0-ae58b71cfb-3a8d57e0ab.zip
  .yarn/cache/dont-sniff-mimetype-npm-1.1.0-a48efd8b1e-9a4ef261db.zip
  .yarn/cache/feature-policy-npm-0.3.0-c1f4998165-7884c24e0c.zip
  .yarn/cache/helmet-crossdomain-npm-0.4.0-9b1b0a25d9-ad484f3bfa.zip
  .yarn/cache/helmet-csp-npm-2.10.0-bde31814fe-27a7a78df3.zip
  .yarn/cache/helmet-npm-3.23.3-e2bde7fcb5-7883e0e13e.zip
  .yarn/cache/hide-powered-by-npm-1.1.0-d58b0e26be-6c6a5f2205.zip
  .yarn/cache/hpkp-npm-2.0.0-6cacef2064-01f8df366e.zip
  .yarn/cache/hsts-npm-2.2.0-a60ebe6f36-e8d265c30b.zip
  .yarn/cache/nocache-npm-2.1.0-cb459f771c-702ad516a7.zip
  .yarn/cache/referrer-policy-npm-1.2.0-4cd0b1676f-520a112f3a.zip
  .yarn/cache/x-xss-protection-npm-1.3.0-b21b288d58-acfce146b7.zip
  app.js
  audit.json
  package.json
  yarn.lock
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-816

#821 Test revert
  .pnp.cjs
  .yarn/cache/bowser-npm-2.9.0-043d25ec0d-ffb068f11e.zip
  .yarn/cache/camelize-npm-1.0.0-5eda108776-769f8d1007.zip
  .yarn/cache/content-security-policy-builder-npm-2.1.0-0bb05bcc01-375944b111.zip
  .yarn/cache/dasherize-npm-2.0.0-ae58b71cfb-3a8d57e0ab.zip
  .yarn/cache/dont-sniff-mimetype-npm-1.1.0-a48efd8b1e-9a4ef261db.zip
  .yarn/cache/feature-policy-npm-0.3.0-c1f4998165-7884c24e0c.zip
  .yarn/cache/helmet-crossdomain-npm-0.4.0-9b1b0a25d9-ad484f3bfa.zip
  .yarn/cache/helmet-csp-npm-2.10.0-bde31814fe-27a7a78df3.zip
  .yarn/cache/helmet-npm-3.23.3-e2bde7fcb5-7883e0e13e.zip
  .yarn/cache/hide-powered-by-npm-1.1.0-d58b0e26be-6c6a5f2205.zip
  .yarn/cache/hpkp-npm-2.0.0-6cacef2064-01f8df366e.zip
  .yarn/cache/hsts-npm-2.2.0-a60ebe6f36-e8d265c30b.zip
  .yarn/cache/nocache-npm-2.1.0-cb459f771c-702ad516a7.zip
  .yarn/cache/referrer-policy-npm-1.2.0-4cd0b1676f-520a112f3a.zip
  .yarn/cache/x-xss-protection-npm-1.3.0-b21b288d58-acfce146b7.zip
  app.js
  audit.json
  package.json
  yarn.lock
Labels: ns:pcq, prd:pcq, keep-helm, enable_keep_helm, rel:pcq-frontend-pr-821

#826 PCQ-1864 - added 3 fingerprints into audit.json file
  audit.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-826

#837 PCQ-1853 change script for non production env
  app/views/includes/scripts.html
  package.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-837

#841 PCQ-1864 fix securityscan 22-01-2024
  audit.json
  package.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-841

#844 PCQ-1864 fixing more securing scan
  audit.json
  package.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-844

#845 PCQ-1864 security scan fix
  audit.json
  package.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-845

#846 Update scripts.html
  app/views/includes/scripts.html
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-846

#849 PCQ-1864 removing extra comma
  audit.json
  package.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-849

#854 sort audit.json file
  audit.json
  package.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-854

#862 Ignore zaproxy raised issues
  audit.json
  package.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-862

#863 Ignore ruxitagentjs urls in zaproxy
  Jenkinsfile_nightly
  audit.json
  package.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-863
