Repository hmcts/pcq-frontend, pull requests merged in 2024-08, with the labels that each got.

#1155 back to service to return a 200 json response
  app/middleware/startPageBackService.js
  package.json
Labels: ns:pcq, prd:pcq, enable_keep_helm, rel:pcq-frontend-pr-1155

#1158 wait for fetch to finish before going back
  app/assets/javascripts/back-button.js
  package.json
Labels: ns:pcq, prd:pcq, aat/add-or-update, prod/no-changes, rel:pcq-frontend-pr-1158

#1165 update app insights to version 3
  .pnp.cjs
  app/components/app-insights.js
  app/setupSecrets.js
  charts/pcq-frontend/Chart.yaml
  charts/pcq-frontend/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  package.json
  yarn.lock
Labels: ns:pcq, prd:pcq, do not merge, keep-helm, enable_keep_helm, aat/add-or-update, prod/no-changes, rel:pcq-frontend-pr-1165

#1175 upgraded mocha and stryker mutations
  .pnp.cjs
  package.json
  test/mutation/stryker.conf.js
  yarn.lock
Labels: ns:pcq, prd:pcq, aat/add-or-update, prod/no-changes, rel:pcq-frontend-pr-1175

#1184 revert webdriverio
  .pnp.cjs
  package.json
  yarn.lock
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-1184

#1194 PCQ-1969 adding tracer on continue to question button
  app/middleware/continueToQuestions.js
  app/routes.js
  package.json
Labels: ns:pcq, prd:pcq, enable_keep_helm, rel:pcq-frontend-pr-1194
