Repository hmcts/pcq-frontend, pull requests merged in 2024-06, with the labels that each got.

#1061 Suppress ip vulnerability as there is no fix for it yet
  package.json
  yarn-audit-known-issues
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-1061

#1076 PCQ-1727 updating service down link
  app/registeredServices.json
  package.json
  test/unit/testShutterPage.js
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-1076

#1072 PCQ-1651 address sonar raised issues
  app/components/error.js
  app/components/logger.js
  app/core/steps/Step.js
  app/utils/FeatureToggle.js
  app/views/widgets/addresslookup.html
  app/views/widgets/checkanswer.njk
  app/views/widgets/fielderror.html
  app/views/widgets/lists.html
  app/views/widgets/taskheader.html
Labels: ns:pcq, prd:pcq, enable_keep_helm, rel:pcq-frontend-pr-1072

#1084 PCQ-1852 gov uk library upgrade
  .pnp.cjs
  package.json
  yarn.lock
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-1084

#1077 PCQ-1903 remove DA config
  app/journeys/prl_da.js
  app/registeredServices.json
  app/setupSecrets.js
  config/custom-environment-variables.yaml
  config/default.yaml
  test/unit/core/testServiceData.json
  test/unit/services/testServiceInvokerData.json
  test/unit/utils/testInvoker.js
Labels: ns:pcq, prd:pcq, enable_keep_helm, rel:pcq-frontend-pr-1077

#1089 PCQ-1852 revert back govuk-frontend 4.8.0
  .pnp.cjs
  app/views/includes/layout.html
  package.json
  yarn.lock
Labels: ns:pcq, prd:pcq, enable_keep_helm, rel:pcq-frontend-pr-1089

#1088 Pcq 1852
  .pnp.cjs
  app.js
  app/views/includes/scripts.html
  package.json
  yarn.lock
Labels: ns:pcq, prd:pcq, enable_keep_helm, rel:pcq-frontend-pr-1088

#1092 Pcq 1852
  app/views/includes/layout.html
  package.json
  yarn.lock
Labels: ns:pcq, prd:pcq, enable_keep_helm, rel:pcq-frontend-pr-1092

#1097 PCQ-1758 adding track trace in entering journey
  app.js
  app/components/app-insights.js
  app/middleware/registerIncomingService.js
  package.json
Labels: ns:pcq, prd:pcq, enable_keep_helm, aat/add-or-update, prod/no-changes, rel:pcq-frontend-pr-1097

#1102 PCQ-1758 missing function call
  app.js
  app/components/app-insights.js
  package.json
Labels: ns:pcq, prd:pcq, enable_keep_helm, rel:pcq-frontend-pr-1102

#1103 PCQ-1906 start page text
  app/resources/cy/translation/variable/prl_ca.json
  app/resources/en/translation/variable/prl_ca.json
  package.json
  test/unit/core/testServiceData.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-1103

#1108 PCQ-1907 revert back mocha
  .pnp.cjs
  .pnp.loader.mjs
  package.json
  yarn.lock
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-1108
