Repository hmcts/pcq-frontend, pull requests merged in 2024-03, with the labels that each got.

#926 PCQ-1811 applicationInsight upgrade
  package.json
  yarn.lock
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-926

#930 Pcq 1817 UUID upgrde
  .pnp.cjs
  app.js
  app/middleware/initSession.js
  app/utils/Invoker.js
  package.json
  test/end-to-end/helpers/TestConfigurator.js
  test/end-to-end/smoke/smoketest.js
  yarn.lock
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-930

#938 PCQ-1817 nodemon upgrade
  .pnp.cjs
  package.json
  yarn.lock
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-938

#944 PCQ-1817 remove date-time from add format
  app/core/steps/ValidationStep.js
  package.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-944

#943 PCQ-1817 revert ajv upgrade
  .pnp.cjs
  app/components/error.js
  app/core/steps/ValidationStep.js
  package.json
  yarn.lock
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-943

#947 PCQ-1740 codecptjs upgrade
  package.json
  yarn.lock
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-947

#958 Bump puppeteer
  .pnp.cjs
  package.json
  yarn.lock
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-958

#955 PCQ-1858 update accessibility statement
  app/resources/en/translation/static/accessibility.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-955

#967 PCQ-1878 enable pcq-frontend for spotInstaces in lower evironment
  charts/pcq-frontend/Chart.yaml
  charts/pcq-frontend/values.yaml
  package.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-967

#968 PCQ-1880 autoscaling
  charts/pcq-frontend/Chart.yaml
  charts/pcq-frontend/values.yaml
  package.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-968

#871 Update language question
  app/resources/cy/translation/language.json
  app/resources/en/translation/language.json
  app/steps/ui/language/schema.json
  app/steps/ui/language/template.html
  test/component/testLanguage.js
  test/end-to-end/pages/language/english.js
  test/end-to-end/pages/steps.js
  test/end-to-end/step_definitions/probatepcqjourney.js
Labels: ns:pcq, prd:pcq, keep-helm, enable_keep_helm, rel:pcq-frontend-pr-871

#974 PCQ-1880 maxReplica to 2 on lower env
  charts/pcq-frontend/Chart.yaml
  charts/pcq-frontend/values.yaml
  package.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-974

#971 Pcq 1858
  .pnp.cjs
  app/resources/cy/translation/static/accessibility.json
  app/resources/en/translation/static/accessibility.json
  app/steps/ui/static/accessibility/template.html
  package.json
  yarn.lock
Labels: ns:pcq, prd:pcq, add-or-update, enable_keep_helm, rel:pcq-frontend-pr-971

#979 PCQ-1893 - added 4 fingerprints into audit.json file
  audit.json
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-979
