Repository hmcts/pcq-frontend, pull requests merged in 2025-05, with the labels that each got.

#1487 Add focus to privacy policy link
  app/resources/en/translation/startpage.json
  charts/pcq-frontend/Chart.yaml
  charts/pcq-frontend/values.preview.template.yaml
  package.json
Labels: ns:pcq, prd:pcq, keep-helm, enable_keep_helm, rel:pcq-frontend-pr-1487

#1492 PCQ-2015 set correct language in html tag
  app.js
  app/views/includes/layout.html
  package.json
Labels: ns:pcq, prd:pcq, enable_keep_helm, rel:pcq-frontend-pr-1492

#1490 Pcq 2016 welsh link
  app/views/includes/footer_links.html
Labels: ns:pcq, prd:pcq, keep-helm, enable_keep_helm, rel:pcq-frontend-pr-1490

#1493 Remove aria label
  app/resources/en/translation/common.json
  package.json
Labels: ns:pcq, prd:pcq, keep-helm, enable_keep_helm, rel:pcq-frontend-pr-1493

#1501 PCQ-2023 Update accessibility statement.
  app/resources/cy/translation/static/accessibility.json
  app/resources/en/translation/static/accessibility.json
  config/default.yaml
  package.json
Labels: ns:pcq, prd:pcq, keep-helm, enable_keep_helm, rel:pcq-frontend-pr-1501

#1513 CME-518 replace jitpack with azure
  test/java/build.gradle
Labels: ns:pcq, prd:pcq, rel:pcq-frontend-pr-1513
